[package]
name = "quick-calc"
version = "0.2.0"
authors = ["RJ Rybarczyk <rj@rybar.tech>"]
description = "A CLI tool for quick decimal, hexadecimal, binary, and octal calcs"
edition = "2018"

[[bin]]
name = "qcal"
path = "src/main.rs"

[dependencies]
