[package]
name = "quick-calc"
version = "0.1.0"
authors = ["RJ Rybarczyk <rj@rybar.tech>"]
descrpition = "A CLI tool for quick decimal, hexadecimal, binary, and octal calcs"
edition = "2018"

[[bin]]
name = "qcal"
path = "src/main.rs"

[dependencies]
structopt = "*"
